// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Migrations;

namespace api.Migrations
{
    [DbContext(typeof(InsuranceContext))]
    [Migration("20211004035033_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("papaya")
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("api.Models.Insurance", b =>
                {
                    b.Property<string>("ClaimCaseId")
                        .HasColumnType("text")
                        .HasColumnName("claim_case_id");

                    b.Property<DateTime>("AdmittedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("admitted_at");

                    b.Property<DateTime>("DischargedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("discharged_at");

                    b.Property<string>("HasFraud")
                        .HasColumnType("text")
                        .HasColumnName("has_fraud");

                    b.Property<string>("HospitalName")
                        .HasColumnType("text")
                        .HasColumnName("hospital_name");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("ClaimCaseId");

                    b.HasIndex("ClaimCaseId")
                        .IsUnique();

                    b.HasIndex("UserName");

                    b.ToTable("insurance");
                });
#pragma warning restore 612, 618
        }
    }
}
