name: .NET

on:
  pull_request:
    branches: [ main ]

jobs:
  test_pull_request:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore "./api.csproj"
      working-directory: src/api
    - name: Build
      run: dotnet build --no-restore "./api.csproj"
      working-directory: src/api
    - name: Test
      run: dotnet test --no-build --verbosity normal "./api.csproj"
      working-directory: src/api
